"""EU-371 (items 2+3): gate hardening on the untrusted-product-code boundary.

Item 2 — ``gate.scan_diff_for_secrets`` honored the ``gate:allow-secret`` pragma on lines ADDED
BY THE VERY DIFF under review (gate.py:347 pre-fix, inside the loop that only ever inspects
``+`` lines), so untrusted product code could whitelist its own secret:
``+API_KEY = "…"  # gate:allow-secret`` scanned clean. The pragma is now honored ONLY for lines
provably pre-existing in the base — the identical (whitespace-stripped) content also appears as
a REMOVED (``-``) or context (`` ``) line of the same diff, which is what a move/reindent of an
already-landed fixture looks like. Those provenance lines are generated by git from BASE content
the diff's author cannot forge, so a NEW pragma-carrying line red-gates and escalates to a human
(build fixtures by concatenation instead — see the gate.py docstring).

Item 3 — GLM_AUTH_TOKEN (the paid z.ai bearer) was inherited by every officer/gate subprocess
that builds/tests untrusted product code: ``backends.is_sensitive_key('GLM_AUTH_TOKEN')`` was
False (the EU-255 boundary stripped Jira/Telegram only). It is now in ``backends.SENSITIVE_KEYS``
so both seams (``gate._subprocess_env`` and ``backends.secret_strip_overrides``) drop it. GLM
runs are unaffected: ``backends.apply()`` reads the token in the PARENT process and hands it to
the child as ``ANTHROPIC_AUTH_TOKEN`` — a different key, untouched by the strip.

Exploit-style (house doctrine, mirrors tests/eu371_guard_glob_test.py): each headline assertion
below is a working bypass on the pre-fix code. All offline — SDK stubbed; no network, no models.
"""
import os
import sys
import tempfile
import types
from pathlib import Path

# Stub the Agent SDK before any orchestrator import (house convention).
sdk = types.ModuleType("claude_agent_sdk")


class _D:
    def __init__(s, *a, **k):
        pass

    def __call__(s, *a, **k):
        return s


sdk.__getattr__ = lambda n: _D
sys.modules["claude_agent_sdk"] = sdk
sys.path.insert(0, ".")

from orchestrator import backends           # noqa: E402
from orchestrator import gate               # noqa: E402
from orchestrator.config import AppConfig   # noqa: E402

results = []


def chk(n, c, d=""):
    results.append((n, bool(c), d))


# Concatenation-built so the credential patterns never appear contiguously in THIS source file —
# otherwise any future self-ticket whose diff adds these lines would red-gate itself on the very
# scanner they test (same convention as tests/deterministic_gates_test.py).
SK_KEY = "sk-" + "a1B2c3D4e5F6g7H8i9J0" + "k1L2m3N4"
AWS_KEY = "AKIA" + "IOSFODNN7EXAMPLE"
PRAGMA = "gate:allow-" + "secret"   # split so this harness's own diff never carries a live pragma

# ══════════════════════════════════════════════════════════════════════════════
# Item 2 — the self-whitelist bypass is closed
# ══════════════════════════════════════════════════════════════════════════════
_secret_line = f'API_KEY = "{SK_KEY}"  # {PRAGMA}'

# 1) the headline exploit: a diff that ADDS a secret and its own exemption in one line
hits_self = gate.scan_diff_for_secrets(f"+{_secret_line}\n")
chk("an ADDED gate:allow-secret line is NOT exempt (self-whitelist closed)", hits_self != [],
    str(hits_self))
# 2) the finding is masked (provost doctrine: never print a real secret)
chk("the self-whitelisted secret is MASKED in the report",
    hits_self != [] and all(SK_KEY not in h for h in hits_self), str(hits_self))
# 3) provenance cannot be forged from other ADDED lines — duplicating the pragma line twice
#    in the same diff is still two NEW lines, not a move
chk("an added pragma line duplicated as another ADDED line is still caught",
    gate.scan_diff_for_secrets(f"+{_secret_line}\n+{_secret_line}\n") != [])
# 4) a CHANGED token behind a moved pragma line is NOT exempt (content match must be exact)
_other = f'API_KEY = "{AWS_KEY}{AWS_KEY[:4]}"  # {PRAGMA}'
chk("a moved pragma line with a DIFFERENT token is still caught",
    gate.scan_diff_for_secrets(f"-{_other}\n+{_secret_line}\n") != [])

# The legitimate escape hatch survives: pre-existing fixture lines being moved/reindented.
chk("a MOVED pre-existing pragma line stays exempt (removed + re-added verbatim)",
    gate.scan_diff_for_secrets(f"-{_secret_line}\n+{_secret_line}\n") == [])
chk("a REINDENTED pre-existing pragma line stays exempt (stripped-content match)",
    gate.scan_diff_for_secrets(f"-{_secret_line}\n+        {_secret_line}\n") == [])
chk("a pragma line duplicated from CONTEXT stays exempt (base content in the same hunk)",
    gate.scan_diff_for_secrets(f" {_secret_line}\n+{_secret_line}\n") == [])

# Regression guards on the pre-EU-371 contract that must NOT change.
chk("a plain added secret (no pragma) is still caught",
    gate.scan_diff_for_secrets(f'+key = "{SK_KEY}"\n') != [])
chk("removed/context secrets are still ignored; clean diff → []",
    gate.scan_diff_for_secrets(f'-gone = "{SK_KEY}"\n context = 1\n+x = 1\n') == []
    and gate.scan_diff_for_secrets("") == [])

# 10) integration: the deterministic gate red-gates the self-whitelisting diff end to end
_tmp = Path(tempfile.mkdtemp())
_app = AppConfig(name="a", repo_path=str(_tmp), backlog_backend="none", gate_timeout_sec=30)
_det = gate.run_deterministic_checks(_app, ["src/x.py"], f"+{_secret_line}\n")
chk("run_deterministic_checks red-gates the self-whitelisted secret (SECRET-LEAK)",
    not _det.passed and "SECRET-LEAK" in _det.report, _det.report[:160])
chk("the deterministic report never prints the raw token", SK_KEY not in _det.report)

# ══════════════════════════════════════════════════════════════════════════════
# Item 3 — GLM_AUTH_TOKEN is stripped from untrusted-code subprocess envs
# ══════════════════════════════════════════════════════════════════════════════
_PLANTED_GLM = "zai-test-token-eu371"
_saved_glm = os.environ.get("GLM_AUTH_TOKEN")
os.environ["GLM_AUTH_TOKEN"] = _PLANTED_GLM
try:
    # 11) the predicate itself — the single denylist BOTH seams share (EU-255 architecture)
    chk("is_sensitive_key('GLM_AUTH_TOKEN') is True (was False — the EU-255 gap)",
        backends.is_sensitive_key("GLM_AUTH_TOKEN"))
    # 12) gate seam: the env handed to the product's own test/build commands omits the bearer
    genv = gate._subprocess_env(_app)
    chk("gate._subprocess_env omits GLM_AUTH_TOKEN", "GLM_AUTH_TOKEN" not in genv,
        genv.get("GLM_AUTH_TOKEN"))
    # 13) officer seam: the strip overrides BLANK it (the SDK merges options.env OVER os.environ)
    chk("secret_strip_overrides blanks GLM_AUTH_TOKEN",
        backends.secret_strip_overrides().get("GLM_AUTH_TOKEN") == "")
    # 14-15) the GREEN path: GLM runs still authenticate — the bearer reaches the child under
    # ANTHROPIC_AUTH_TOKEN (written by apply() in the parent), which the strip must never touch
    chk("GLM auth still reaches a GLM child (as ANTHROPIC_AUTH_TOKEN, via _glm_env)",
        backends._glm_env().get("ANTHROPIC_AUTH_TOKEN") == _PLANTED_GLM)
    chk("ANTHROPIC_AUTH_TOKEN itself is NOT sensitive (the injected key must survive the strip)",
        not backends.is_sensitive_key("ANTHROPIC_AUTH_TOKEN"))
    # 16) the gate env is minimized, not gutted — toolchain vars survive
    chk("gate env keeps PATH (minimized, not gutted)", genv.get("PATH") == os.environ.get("PATH"))
    # 17) the ticket's exploit: an env dump inside a REAL gate subprocess shows no bearer
    _seen = _tmp / "glm_seen.txt"
    _script = ("import os,sys;"
               "open(sys.argv[1],'w').write(os.environ.get('GLM_AUTH_TOKEN',''))")
    _res = gate.run_commands(_app, [f"{sys.executable} -c \"{_script}\" {_seen}"])
    chk("run_commands child spawned cleanly", _res.passed, _res.report[:160])
    chk("a real gate subprocess env dump carries NO z.ai bearer",
        _seen.exists() and _seen.read_text() == "",
        _seen.read_text() if _seen.exists() else "<missing>")
finally:
    if _saved_glm is None:
        os.environ.pop("GLM_AUTH_TOKEN", None)
    else:
        os.environ["GLM_AUTH_TOKEN"] = _saved_glm

# ══════════════════════════════════════════════════════════════════════════════
# tally
# ══════════════════════════════════════════════════════════════════════════════
passed = sum(1 for _, ok, _ in results if ok)
print("\n=============== EU-371 GATE HARDENING QA ===============")
for n, ok, det in results:
    print(f"  [{'PASS' if ok else 'FAIL'}] {n}" + (f"  ({det})" if det and not ok else ""))
print("--------------------------------------------------------")
print(f"  {passed}/{len(results)} passed")
print("  RESULT:", "ALL GREEN" if passed == len(results) else f"{len(results) - passed} FAIL")
sys.exit(0 if passed == len(results) else 1)
